### PR TITLE
Docker: copy composer binary from composer image

### PR DESCRIPTION
**Pull request by glensc**
See PR title

### CODE REVIEW

**Comment by glensc** [comment]
Typed this from my phone, test before merge.

**Comment by jenshaase** [comment]
As far as I understand this change, it requires to have another container call "composer". But this may not be the case for everyone? Or did I miss something?

**Comment by glensc** [comment]
@jenshaase yes, you miss something.

docs:
- https://docs.docker.com/engine/reference/builder/#copy

if you test building from this branch, you'll see how it behaves.

**Comment by glensc** [comment]
Tested myself, looks as expected

```
$ docker build https://raw.githubusercontent.com/glensc/phel-scaffolding/patch-1/build/Dockerfile -t test
$ docker run --rm -it test composer --version
Composer version 2.0.9 2021-01-27 16:09:27
```

```
➔ docker history test
IMAGE          CREATED              CREATED BY                                      SIZE      COMMENT
fdf53d1fe8d5   About a minute ago   WORKDIR /srv/phel-scaffolding                   0B        buildkit.dockerfile.v0
<missing>      About a minute ago   RUN /bin/sh -c useradd -m dev # buildkit        334kB     buildkit.dockerfile.v0
<missing>      About a minute ago   COPY /usr/bin/composer /usr/bin/composer # b…   2.21MB    buildkit.dockerfile.v0
<missing>      About a minute ago   RUN /bin/sh -c apt-get update &&     apt-get…   62.5MB    buildkit.dockerfile.v0
<missing>      12 days ago          /bin/sh -c #(nop)  CMD ["php-fpm"]              0B
<missing>      12 days ago          /bin/sh -c #(nop)  EXPOSE 9000                  0B
...
```

**Comment by jenshaase** [comment]
Ah, cool. Now I understand it. Thanks for the improvement. I will merge it!

**Comment by glensc** [comment]
also, you shouldn't do `apt-get upgrade -y` in Dockerfiles. the base image you are using is updated regularly and the command adds extra size to the image, and may even break things, as some packages are not upgradeable.

but as this build result is not published not a big issue.

skim through Dockerfile best practices:
- https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

**Comment by Chemaclass** [comment]
@glensc do you suggest to change
```bash
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git
```
to simply this?
```bash
RUN apt-get install -y git
```

**Comment by glensc** [comment]
@Chemaclass no, you still need `apt-get update` to get package indexes, see an example:
- https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#sort-multi-line-arguments

**Comment by glensc** [comment]
There's "apt-get" section under "run" section, explaining it all:
- https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run

**Comment by glensc** [comment]
also, you don't need ` && rm -rf /var/lib/apt/lists/*` if using an official Debian image, which I think your php base image does:

> Official Debian and Ubuntu images automatically run apt-get clean, so explicit invocation is not required.

**Pull request merged**
